name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }}/ruby-${{ matrix.ruby }}/python-${{ matrix.python }}-${{ matrix.python_architecture }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - macos-latest
        ruby:
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        python:
        - 3.8.x
        - 3.7.x
        - 3.6.x
        - 2.7.x
        python_architecture:
        - x64

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: ruby/setup-ruby@v1
      if: matrix.ruby_version != 'master-nightly'
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_architecture }}

    - run: gem install bundler

    - run: pip install --user numpy

    - run: bundle install

    - run: bundle exec rake compile

    - run: python lib/pycall/python/investigator.py

    - run: bundle exec rake
      env:
        PYTHON: python
